define({
	COLLISION_IDENTIFIER_PLAYER: 		     'player',
	COLLISION_IDENTIFIER_PLAYER_HEAD: 	     'head',
	COLLISION_IDENTIFIER_PLAYER_CHEST: 	     'chest',
	COLLISION_IDENTIFIER_PLAYER_LEGS: 	     'legs',
	COLLISION_IDENTIFIER_PLAYER_FOOT_SENSOR: 'footsensor',

	COLLISION_IDENTIFIER_TILE: 'tile'	     
});